permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: zc
  email: 154587940@qq.com 
  link: http://baidu.com
  weibo: http://weibo.com/u/1827828847
  github: http://github.com/zc001

# 站点信息
title: zc的博客 
description: zc的博客
url: http://baidu.com
#rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/ava.png
favicon: /public/img/ava.png

# google analytics 设置
# ga:
#   id: UA-54767140-1
#   url: yansu.org

# # disqus 设置
disqus:
  shortname: zc001

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - node模块
  - javaScript
  # - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
